# Generated by Django 3.1.1 on 2020-11-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testApp', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('toppings', models.ManyToManyField(to='testApp.Topping')),
            ],
        ),
    ]
